In [1]:
import numpy as np

# Question 1 :
* Écrire un programme qui produit un tableau à une dimension avec 100 éléments qui sont les nombres pairs entre 2 et 200

In [2]:
tab=np.arange(2,201,2)

In [3]:
tab

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

In [4]:
len(tab)

100

# Question 2
*  Créez un tableau NumPy de taille 10X10 qui représente la table de multiplication

In [5]:
# la meilleur methode: np.fromfunction (voir le help)
# nous on va cree un tableau 10x10 que l'on va remplir avec une boucle for 
# on privilegie les solutions a haut apport algorithmique

In [6]:
tab_mult=np.zeros((10,10),dtype=int)
for i in range(1,11):
    for j in range(1,11):
        tab_mult[i-1,j-1]=i*j


In [7]:
tab_mult

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

# Question 3
* À partir du tableau de la table de multiplication de la question 2, affichez que les diagonales (c'est-à-dire uniquement les nombres 1, 4, 9, 16 et ainsi de suite). Utilisez le masque booléen

In [8]:
# puisque 0==False et 1==True 
#        on convertie la matrice identite en matrice booleen 
#           ce serra elle notre masque booleen

In [9]:
masque=np.eye(10).astype(bool) 
diag_mult=tab_mult[masque]

In [10]:
diag_mult

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

# Question 4
* Construisez un tableau de 10 entiers sélectionnés au hasard (entre 1 à 100) et affichez uniquement les nombres impairs.

In [11]:
tab_random=np.random.randint(1,101,size=10)

In [12]:
print(f"Tableau aleatoire :\t {tab_random}")# les fstring sont tres pratique, faire une recherche google
print(f" elements impaires:  \t {tab_random[tab_random %2==1]}")

Tableau aleatoire :	 [ 1 44 26 40  7 31 16 25  3 72]
 elements impaires:  	 [ 1  7 31 25  3]


# Question 5
* Construisez un tableau de 10 entiers sélectionnés au hasard (entre 1 à 100) et trouvez le plus petit nombre supérieur à 50

In [13]:
# methode 1
#  filtrer notre tableau avec les masques  booleen 
#        et laisser np.min faire le reste
# methode 2 on privilegie les algorithmes

In [14]:
tab_random=np.random.randint(1,101,size=10)
my_min=np.nan # essentiellement c'est pour le cas << tous les elements <50 >> , toute valeur negative conviendrais aussi ...

In [15]:
for i in tab_random:
    if i>=50 and (np.isnan(my_min)or i<my_min):
        my_min=i
        # si i >=50 et que c'est le premier de ceux la qu'on rencontre, 
        #     alors my_min=i
        # si i>=50 et que il est plus petit que notre min actuel,
        #     alors il prend sa place

In [16]:
print(f"tableau alleatoire:\t {tab_random}")
if not (np.isnan(my_min)): # en gros si my_min n'est pas un nan
    print(f" le plus petit element >=50 est ===> \t  {my_min}")
else:
    print("pas de candidat >=50 :===> !!!!!!!!!! \t")

tableau alleatoire:	 [58 56 35 36 74 26 26 27 37 15]
 le plus petit element >=50 est ===> 	  56


# Question 6
* Construisez un tableau de 10 entiers choisis au hasard (entre 1 à 100) et trouvez les cinq plus grands nombres.

In [17]:
# la encore 2 methodes
#   methode 2 :  
#    on parcour 5 fois pour trouver 5 max
#        on s'assure que l'on trouve pas le meme max plusieurs fois sauf si l'element est duplique dans tab_random

In [18]:
tab_random=np.random.randint(1,101,size=10)
#  le cas <<doublons>> rend le code delicat
# pour s'en rendre compte prendre :<< tab_random=np.array([2,4,5,8,5,8,8,4,4,1]) >>

In [19]:
tab_max_5=np.zeros(shape=5,dtype=np.int32)
copy_tab=np.copy(tab_random) # on va <<supprimer>> des elements,il faut donc surtout pas prendre une vue du tab
for ind_5 in range (5):       #    supprimmer = remplacer par -1
    nb_max=-1 #on exploite le fait que les elements du tab sont >=0
    tmp_max=0 # pour me stocker l'indice de mon max ...
    for i in range(copy_tab.size):
        if copy_tab[i]> nb_max :
            nb_max=copy_tab[i] # A ameliorer:Comment trouvr l'indice du premier occurence d'un element ? la methode .where me fait n'importe quoi
            tmp_max=i
    copy_tab[tmp_max]=-1 # chaque max trouve deviens -1
    if nb_max !=-1:
            tab_max_5[ind_5]=nb_max

In [20]:
print(f" Tableau de depart: \t{tab_random}")

 Tableau de depart: 	[90 59 96 71 56 54 37  1 24 79]


In [21]:
print(f" Tableau des 5 plus grands:==>  \t{tab_max_5}")

 Tableau des 5 plus grands:==>  	[96 90 79 71 59]


# Fin partie Numpy